[project]
name = "wumpus-world"
description = "Wumpus World CodeWars kata solution in Python"
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "pytest>8.3.4"
]


[tool.pytest.ini_options]
addopts = "-v"